import { ArrowLeft, ImageOff, LandPlot, RotateCcw } from 'lucide-react';
import { SavedItem } from '../types';
import { formatDecimal, formatHillsWords, formatTeraiWords } from '../utils/conversions';
import { useAppLanguage } from '../utils/useAppLanguage';

interface Props { project: SavedItem; onBack: () => void; onStartNew: () => void; onVisualize: (sqFt: number) => void; }

const SavedMeasurementReview = ({ project, onBack, onStartNew, onVisualize }: Props) => {
  const language=useAppLanguage(); const ne=language==='ne';
  const boundary=project.source?.boundary??[]; const width=project.source?.imageWidth??1000; const height=project.source?.imageHeight??750;
  const confidence=project.source?.confidence ? (ne?(project.source.confidence==='HIGH'?'उच्च विश्वसनीयता':project.source.confidence==='MEDIUM'?'मध्यम विश्वसनीयता':'कम विश्वसनीयता'):`${project.source.confidence.toLowerCase()} confidence`) : '';
  return <div className="page-shell animate-enter">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={onBack} className="button-secondary focus-ring"><ArrowLeft size={16}/>{ne?'परियोजना':'Projects'}</button><div className="flex flex-wrap gap-2"><button type="button" onClick={onStartNew} className="button-secondary focus-ring"><RotateCcw size={16}/>{ne?'नयाँ रेखा सुरु':'Start new trace'}</button><button type="button" onClick={()=>onVisualize(project.sqFt)} className="button-primary focus-ring"><LandPlot size={16}/>{ne?'यो क्षेत्रफल योजना':'Plan this area'}</button></div></div>
    <header className="page-header"><p className="eyebrow">{ne?'सुरक्षित तस्बिर अनुमान':'Saved image estimate'}</p><h1 className="page-title">{project.title}</h1><p className="page-copy">{ne?'रेखा र स्केल स्थानीय रूपमा सुरक्षित छन्। गोपनीयताका लागि मूल तस्बिर राखिएको छैन, त्यसैले यो मूल स्क्रिनसट होइन, पुनर्निर्मित सिमाना समीक्षा हो।':'The traced geometry and calibration were saved locally. The original uploaded image was intentionally not retained, so this is a reconstructed boundary review rather than the original screenshot.'}</p></header>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_24rem]">
      <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-paper-200 px-5 py-4"><div><p className="section-title">{ne?'पुनर्निर्मित सिमाना':'Reconstructed boundary'}</p><p className="section-copy">{ne?'मूल तस्बिरको अनुपातअनुसार।':'Proportional to the original image dimensions.'}</p></div><ImageOff className="text-ink-400" size={20}/></div><div className="min-h-[420px] bg-ink-950 p-4"><svg viewBox={`0 0 ${width} ${height}`} className="h-full min-h-[390px] w-full" role="img" aria-label={ne?`${boundary.length} बिन्दु भएको सुरक्षित बहुभुज`:`Saved polygon with ${boundary.length} points`}><rect width={width} height={height} fill="#10231d"/><path d={boundary.length?`M ${boundary.map(point=>`${point.x},${point.y}`).join(' L ')} Z`:''} fill="rgba(0,56,147,.28)" stroke="#8baeff" strokeWidth={Math.max(3,width*.003)}/>{boundary.map((point,index)=><g key={index}><circle cx={point.x} cy={point.y} r={Math.max(6,width*.006)} fill="#003893" stroke="white" strokeWidth="3"/><text x={point.x} y={point.y-Math.max(10,width*.01)} textAnchor="middle" fontSize={Math.max(12,width*.014)} fontWeight="700" fill="white">{index+1}</text></g>)}</svg></div></section>
      <aside className="space-y-4"><section className="panel p-5"><p className="metric-label">{ne?'अनुमानित क्षेत्रफल':'Estimated area'}</p><p className="numeral mt-2 text-4xl font-semibold text-ink-950">{formatDecimal(project.sqFt)} <span className="text-sm text-ink-400">{ne?'वर्ग फिट':'sq ft'}</span></p><p className="mt-1 text-sm text-ink-500">{formatDecimal(project.sqM)} m²</p>{confidence&&<span className="status-pill status-warning mt-4">{confidence}</span>}</section><section className="panel p-5"><Result label={ne?'पहाडी प्रणाली':'Hill system'} value={formatHillsWords(project.sqFt)}/><Result label={ne?'तराई प्रणाली':'Terai system'} value={formatTeraiWords(project.sqFt)}/><Result label={ne?'परिधि':'Perimeter'} value={project.source?.perimeterFt?`${formatDecimal(project.source.perimeterFt)} ft`:(ne?'रेकर्ड छैन':'Not recorded')}/><Result label={ne?'सिमाना बिन्दु':'Boundary points'} value={String(boundary.length)}/><Result label={ne?'सन्दर्भ दूरी':'Reference distance'} value={project.source?.referenceDistanceFt?`${formatDecimal(project.source.referenceDistanceFt)} ft`:(ne?'रेकर्ड छैन':'Not recorded')}/></section><p className="rounded-lg border border-saffron-200 bg-saffron-50 p-4 text-xs leading-5 text-ink-600">{ne?'यो पुनर्निर्माण अनुमान हो, कानुनी नापी होइन। बिन्दु सच्याउन मूल तस्बिर फेरि अपलोड गरी नयाँ रेखा कोर्नुहोस्।':'This reconstruction is an estimate, not a legal survey. Re-upload the original image and trace again when you need to adjust vertices.'}</p></aside>
    </div>
  </div>;
};
const Result=({label,value}:{label:string;value:string})=><div className="border-b border-paper-200 py-3 last:border-0"><p className="metric-label">{label}</p><p className="mt-1 text-sm font-semibold text-ink-800">{value}</p></div>;
export default SavedMeasurementReview;
