import { useEffect, useMemo, useRef, useState, type ChangeEvent, type KeyboardEvent } from 'react';
import { Bookmark, Check, Copy, Download, Eye, FileJson, FileUp, GitCompare, Printer, Search, Trash2, X } from 'lucide-react';
import { normalizeItems } from '../lib/storage';
import { SavedFilter, SavedItem } from '../types';
import { formatDecimal, formatHillsWords, formatTeraiWords } from '../utils/conversions';
import { projectToGeoJson, projectToGpx, projectToKml } from '../utils/geospatial';
import { escapeHtml, MAX_IMPORT_BYTES, MAX_IMPORT_PROJECTS, safeCsvCell, safeDownloadName } from '../utils/security';
import { useAppLanguage } from '../utils/useAppLanguage';
import SegmentedControl from './SegmentedControl';

interface Props { items: SavedItem[]; onDelete: (id:string)=>void; onOpen:(item:SavedItem)=>void; onClearAll:()=>void|Promise<void>; onImport:(items:SavedItem[])=>number; notify:(message:string)=>void; }
const download=(name:string,content:string,type:string)=>{const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.rel='noopener';link.click();setTimeout(()=>URL.revokeObjectURL(url),0);};

const SavedScreen=({items,onDelete,onOpen,onClearAll,onImport,notify}:Props)=>{
  const language=useAppLanguage();const ne=language==='ne';
  const [filter,setFilter]=useState<SavedFilter>('ALL');const[query,setQuery]=useState('');const[selected,setSelected]=useState<string[]>([]);const[confirmClear,setConfirmClear]=useState(false);
  const importRef=useRef<HTMLInputElement>(null);const compareCloseRef=useRef<HTMLButtonElement>(null);const clearCancelRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{setSelected(current=>current.filter(id=>items.some(item=>item.id===id)));},[items]);
  useEffect(()=>{if(selected.length!==2)return undefined;compareCloseRef.current?.focus();const close=(event:globalThis.KeyboardEvent)=>{if(event.key==='Escape')setSelected([]);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[selected.length]);
  useEffect(()=>{if(!confirmClear)return undefined;clearCancelRef.current?.focus();const close=(event:globalThis.KeyboardEvent)=>{if(event.key==='Escape')setConfirmClear(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[confirmClear]);
  const filtered=useMemo(()=>items.filter(item=>{const matchesFilter=filter==='ALL'||item.type===filter;const searchable=`${item.title} ${formatDecimal(item.sqFt)} ${item.tags.join(' ')} ${item.notes??''}`.toLowerCase();return matchesFilter&&searchable.includes(query.trim().toLowerCase());}),[filter,items,query]);
  const comparison=selected.length===2?selected.map(id=>items.find(item=>item.id===id)).filter(Boolean)as SavedItem[]:[];
  const toggle=(id:string)=>setSelected(current=>current.includes(id)?current.filter(item=>item!==id):current.length<2?[...current,id]:[current[1],id]);
  const summary=(item:SavedItem)=>ne?`${item.title}\n${formatDecimal(item.sqFt)} वर्ग फिट · ${formatDecimal(item.sqM)} वर्ग मिटर\nपहाडी: ${formatHillsWords(item.sqFt)}\nतराई: ${formatTeraiWords(item.sqFt)}${item.source?.perimeterFt?`\nपरिधि: ${formatDecimal(item.source.perimeterFt)} फिट`:''}`:`${item.title}\n${formatDecimal(item.sqFt)} sq ft · ${formatDecimal(item.sqM)} sq m\nHill: ${formatHillsWords(item.sqFt)}\nTerai: ${formatTeraiWords(item.sqFt)}${item.source?.perimeterFt?`\nPerimeter: ${formatDecimal(item.source.perimeterFt)} ft`:''}`;
  const copy=async(item:SavedItem)=>{try{await navigator.clipboard.writeText(summary(item));notify(ne?'सुरक्षित परियोजना प्रतिलिपि भयो।':'Saved project copied.');}catch{notify(ne?'ब्राउजरले क्लिपबोर्ड पहुँच रोक्यो।':'Your browser blocked clipboard access.');}};
  const exportProject=(item:SavedItem)=>download(`${safeDownloadName(item.title)}.json`,JSON.stringify({app:'Napiyo',version:3,exportedAt:new Date().toISOString(),project:item},null,2),'application/json');
  const exportAll=()=>download('napiyo-projects-backup.json',JSON.stringify({app:'Napiyo',version:3,exportedAt:new Date().toISOString(),projects:items},null,2),'application/json');
  const exportCsv=()=>{const rows=[ne?['शीर्षक','प्रकार','वर्ग फिट','वर्ग मिटर','पहाडी प्रणाली','तराई प्रणाली','परिधि फिट','मिति']:['Title','Type','Square feet','Square metres','Hill system','Terai system','Perimeter feet','Date'],...items.map(item=>[item.title,item.type,String(item.sqFt),String(item.sqM),formatHillsWords(item.sqFt),formatTeraiWords(item.sqFt),String(item.source?.perimeterFt??''),new Date(item.date).toISOString()])];download('napiyo-projects.csv',rows.map(row=>row.map(safeCsvCell).join(',')).join('\n'),'text/csv;charset=utf-8');};
  const importProjects=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>MAX_IMPORT_BYTES)return notify(ne?'ब्याकअप धेरै ठूलो छ। ८ MB भन्दा सानो JSON प्रयोग गर्नुहोस्।':'That backup is too large. Use a JSON file smaller than 8 MB.');try{const parsed:unknown=JSON.parse(await file.text());const raw=Array.isArray(parsed)?parsed:parsed&&typeof parsed==='object'&&'projects'in parsed?(parsed as{projects?:unknown}).projects:parsed&&typeof parsed==='object'&&'project'in parsed?[(parsed as{project?:unknown}).project]:[];if(Array.isArray(raw)&&raw.length>MAX_IMPORT_PROJECTS)return notify(ne?`ब्याकअपमा अधिकतम ${MAX_IMPORT_PROJECTS} परियोजना हुन सक्छ।`:`A backup may contain at most ${MAX_IMPORT_PROJECTS} projects.`);const projects=Array.isArray(raw)?normalizeItems(raw):[];if(!projects.length)return notify(ne?'फाइलमा मान्य Napiyo परियोजना भेटिएन।':'No valid Napiyo projects were found in that file.');const count=onImport(projects);notify(count?(ne?`${count} परियोजना पुनःस्थापित भयो।`:`${count} project${count===1?'':'s'} restored.`):(ne?'परियोजना पुनःस्थापित गर्न सकिएन।':'The projects could not be restored.'));}catch{notify(ne?'ब्याकअप फाइल मान्य JSON होइन।':'That backup file is not valid JSON.');}};
  const exportGeo=(item:SavedItem,kind:'geojson'|'kml'|'gpx')=>{const points=item.source?.geoPoints;if(!points?.length)return notify(ne?'भौगोलिक निर्यात GPS परियोजनाका लागि मात्र उपलब्ध छ।':'Geospatial export is available for GPS projects.');const values={geojson:[projectToGeoJson(item.title,points),'application/geo+json'],kml:[projectToKml(item.title,points),'application/vnd.google-earth.kml+xml'],gpx:[projectToGpx(item.title,points),'application/gpx+xml']}as const;download(`${safeDownloadName(item.title)}.${kind}`,values[kind][0],values[kind][1]);};
  const printReport=(item:SavedItem)=>{const report=window.open('','_blank','noopener,noreferrer');if(!report)return notify(ne?'ब्राउजरले प्रिन्ट रिपोर्ट रोक्यो।':'The browser blocked the printable report.');const title=escapeHtml(item.title),type=escapeHtml(item.type),area=escapeHtml(`${formatDecimal(item.sqFt)} sq ft · ${formatDecimal(item.sqM)} m²`),hill=escapeHtml(formatHillsWords(item.sqFt)),terai=escapeHtml(formatTeraiWords(item.sqFt)),perimeter=escapeHtml(item.source?.perimeterFt?`${formatDecimal(item.source.perimeterFt)} ft`:(ne?'रेकर्ड छैन':'Not recorded')),savedDate=escapeHtml(new Date(item.date).toLocaleString(ne?'ne-NP':'en')),generatedDate=escapeHtml(new Date().toLocaleDateString(ne?'ne-NP':'en'));report.document.open();report.document.write(`<!doctype html><html lang="${ne?'ne':'en'}"><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><title>${title}</title><style>body{font-family:system-ui,sans-serif;margin:48px;color:#171a21}h1{font-size:30px}table{border-collapse:collapse;width:100%;margin-top:24px}td{border-bottom:1px solid #ddd;padding:12px 0}td:first-child{font-weight:700;width:35%}.note{margin-top:30px;padding:16px;background:#fff7ed;border:1px solid #fed7aa}@media print{button{display:none}}</style></head><body><h1>${title}</h1><p>${ne?'Napiyo बाट तयार गरिएको मिति':'Generated by Napiyo on'} ${generatedDate}</p><table><tr><td>${ne?'परियोजना प्रकार':'Project type'}</td><td>${type}</td></tr><tr><td>${ne?'क्षेत्रफल':'Area'}</td><td>${area}</td></tr><tr><td>${ne?'पहाडी प्रणाली':'Hill system'}</td><td>${hill}</td></tr><tr><td>${ne?'तराई प्रणाली':'Terai system'}</td><td>${terai}</td></tr><tr><td>${ne?'परिधि':'Perimeter'}</td><td>${perimeter}</td></tr><tr><td>${ne?'सुरक्षित मिति':'Saved'}</td><td>${savedDate}</td></tr></table><p class="note">${ne?'योजना सहयोगका लागि मात्र। यो नापी अभिलेख, कानुनी नाप, मूल्याङ्कन वा निर्माण स्वीकृति होइन।':'Planning aid only. This report is not a cadastral record, legal survey, valuation, or construction approval.'}</p><button type="button" onclick="window.print()">${ne?'प्रिन्ट वा PDF सुरक्षित':'Print or save as PDF'}</button></body></html>`);report.document.close();};
  const trapFocus=(event:KeyboardEvent<HTMLElement>)=>{if(event.key!=='Tab')return;const focusable=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')).filter(node=>!node.hasAttribute('disabled'));if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1)!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
  const typeLabel=(item:SavedItem)=>ne?(item.type==='CONVERTED'?'ठ्याक्कै रूपान्तरण':item.type==='MEASURED'?'तस्बिर अनुमान':item.type==='GPS'?'GPS अनुमान':'जग्गा योजना'):(item.type==='CONVERTED'?'Exact conversion':item.type==='MEASURED'?'Image estimate':item.type==='GPS'?'GPS estimate':'Site plan');
  const confidenceLabel=(value:string)=>ne?(value==='HIGH'?'उच्च विश्वसनीयता':value==='MEDIUM'?'मध्यम विश्वसनीयता':'कम विश्वसनीयता'):`${value.toLowerCase()} confidence`;

  if(!items.length)return <div className="page-shell animate-enter"><div className="mx-auto flex min-h-[58vh] max-w-xl flex-col items-center justify-center text-center"><span className="flex h-14 w-14 items-center justify-center rounded-lg border border-paper-200 bg-white text-leaf-700 shadow-card"><Bookmark size={24}/></span><p className="eyebrow mt-6">{ne?'सुरक्षित परियोजना':'Saved projects'}</p><h1 className="mt-2 text-3xl font-bold text-ink-950">{ne?'तपाईंको परियोजना सूची खाली छ।':'Your project library is empty.'}</h1><p className="mt-3 max-w-md text-sm leading-6 text-ink-500">{ne?'रूपान्तरण, तस्बिर नाप, GPS नाप वा योजना सुरक्षित गर्नुहोस्, वा पुरानो JSON ब्याकअप पुनःस्थापित गर्नुहोस्।':'Save a conversion, image trace, GPS measurement, or plan, or restore a previous JSON backup.'}</p><button type="button" onClick={()=>importRef.current?.click()} className="button-primary focus-ring mt-5"><FileUp size={16}/>{ne?'ब्याकअप पुनःस्थापना':'Restore backup'}</button><input ref={importRef} type="file" accept="application/json,.json" onChange={importProjects} className="sr-only"/></div></div>;
  return <div className="page-shell animate-enter"><header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="page-header !mb-0"><p className="eyebrow">{ne?'सुरक्षित परियोजना':'Saved projects'}</p><h1 className="page-title">{ne?'नाप र योजनालाई उपयोगी तथा सजिलै सार्न मिल्ने बनाउनुहोस्।':'Keep measurements useful and portable.'}</h1><p className="page-copy">{ne?'परियोजना खोल्नुहोस्, तुलना, पुनःस्थापना, प्रिन्ट वा निर्यात गर्नुहोस्। डाटा यही ब्राउजरमा रहन्छ र Napiyo ले इन्क्रिप्ट गर्दैन।':'Open, compare, restore, print, or export your projects. Data stays in this browser and is not encrypted by Napiyo.'}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>importRef.current?.click()} className="button-secondary focus-ring"><FileUp size={16}/>{ne?'JSON पुनःस्थापना':'Restore JSON'}</button><button type="button" onClick={exportCsv} className="button-secondary focus-ring"><Download size={16}/>CSV</button><button type="button" onClick={exportAll} className="button-primary focus-ring"><FileJson size={16}/>{ne?'सबै ब्याकअप':'Backup all'}</button><button type="button" onClick={()=>setConfirmClear(true)} className="button-secondary focus-ring text-red-700"><Trash2 size={16}/>{ne?'स्थानीय डाटा खाली':'Clear local data'}</button><input ref={importRef} type="file" accept="application/json,.json" onChange={importProjects} className="sr-only"/></div></header>
    <section className="panel my-6"><div className="flex flex-col gap-4 p-4 lg:flex-row lg:items-center lg:justify-between"><SegmentedControl label={ne?'सुरक्षित परियोजना फिल्टर':'Filter saved projects'} value={filter} onChange={setFilter} className="w-full lg:w-auto" options={ne?[{label:'सबै',value:'ALL'},{label:'रूपान्तरण',value:'CONVERTED'},{label:'तस्बिर',value:'MEASURED'},{label:'GPS',value:'GPS'},{label:'योजना',value:'PLANNED'}]:[{label:'All',value:'ALL'},{label:'Conversions',value:'CONVERTED'},{label:'Image',value:'MEASURED'},{label:'GPS',value:'GPS'},{label:'Plans',value:'PLANNED'}]}/><label className="relative block w-full lg:max-w-sm"><Search className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-ink-400" size={17}/><span className="sr-only">{ne?'सुरक्षित परियोजना खोज्नुहोस्':'Search saved projects'}</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={ne?'शीर्षक, ट्याग वा क्षेत्रफल खोज्नुहोस्':'Search title, tag, or area'} className="field pl-10"/></label></div></section>
    {!filtered.length?<div className="panel p-10 text-center"><h2 className="section-title">{ne?'मिल्ने परियोजना भेटिएन':'No matching projects'}</h2><p className="section-copy">{ne?'खोज खाली गर्नुहोस् वा अर्को फिल्टर छान्नुहोस्।':'Clear the search or choose another filter.'}</p></div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item=>{const active=selected.includes(item.id);return <article key={item.id} className={`overflow-hidden rounded-lg border bg-white transition ${active?'border-leaf-500 ring-2 ring-leaf-100':'border-paper-300 hover:shadow-card'}`}><button type="button" onClick={()=>toggle(item.id)} aria-pressed={active} className="focus-ring flex w-full items-start justify-between gap-4 p-5 text-left"><div className="min-w-0"><span className={`status-pill ${item.type==='CONVERTED'?'status-positive':'status-warning'}`}>{typeLabel(item)}</span><h2 className="mt-4 truncate text-base font-semibold text-ink-900">{item.title}</h2><p className="numeral mt-3 text-3xl font-semibold text-ink-950">{formatDecimal(item.sqFt)} <span className="text-xs text-ink-400">{ne?'वर्ग फिट':'sq ft'}</span></p><p className="mt-1 text-xs text-ink-500">{formatDecimal(item.sqM)} m²{item.source?.perimeterFt?` · ${formatDecimal(item.source.perimeterFt)} ft ${ne?'परिधि':'perimeter'}`:''}</p>{item.source?.confidence&&<p className="mt-2 text-xs font-semibold uppercase tracking-wide text-ink-400">{confidenceLabel(item.source.confidence)}</p>}</div><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${active?'border-leaf-700 bg-leaf-700 text-white':'border-paper-300 text-transparent'}`}><Check size={13}/></span></button><div className="grid grid-cols-5 gap-px border-t border-paper-200 bg-paper-200"><Action icon={Eye} label={ne?'खोल्नुहोस्':'Open'} onClick={()=>onOpen(item)}/><Action icon={Copy} label={ne?'प्रतिलिपि':'Copy'} onClick={()=>copy(item)}/><Action icon={Printer} label={ne?'रिपोर्ट':'Report'} onClick={()=>printReport(item)}/><Action icon={Download} label={ne?'निर्यात':'Export'} onClick={()=>item.type==='GPS'?exportGeo(item,'geojson'):exportProject(item)}/><Action icon={Trash2} label={ne?'हटाउनुहोस्':'Delete'} danger onClick={()=>onDelete(item.id)}/></div>{item.type==='GPS'&&<div className="flex gap-2 border-t border-paper-200 px-4 py-3">{(['geojson','kml','gpx']as const).map(kind=><button key={kind} type="button" onClick={()=>exportGeo(item,kind)} className="focus-ring rounded-lg border border-paper-300 px-2.5 py-1.5 text-[11px] font-bold uppercase text-ink-600">{kind}</button>)}</div>}</article>;})}</div>}
    {!!selected.length&&<div className="safe-bottom fixed inset-x-4 bottom-22 z-30 mx-auto flex max-w-lg items-center justify-between gap-3 rounded-lg bg-ink-950 p-3 text-white shadow-soft md:bottom-5"><div className="flex items-center gap-3"><GitCompare size={18}/><div><p className="text-sm font-semibold">{selected.length} {ne?'मध्ये २ छानिएको':'of 2 selected'}</p><p className="text-xs text-ink-300">{ne?'तुलना गर्न दुई परियोजना छान्नुहोस्':'Choose two projects to compare'}</p></div></div><button type="button" onClick={()=>setSelected([])} aria-label={ne?'तुलना खाली गर्नुहोस्':'Clear comparison'} className="focus-ring rounded-lg p-2.5 hover:bg-white/10"><X size={18}/></button></div>}
    {comparison.length===2&&<div className="fixed inset-0 z-50 overflow-y-auto bg-ink-950/60 p-4 sm:p-8" role="presentation"><section onKeyDown={trapFocus} className="mx-auto max-w-4xl rounded-lg bg-white p-5 shadow-soft sm:p-7" role="dialog" aria-modal="true" aria-labelledby="compare-title"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">{ne?'परियोजना तुलना':'Project comparison'}</p><h2 id="compare-title" className="mt-2 text-2xl font-bold text-ink-950">{ne?'सुरक्षित क्षेत्रफल तुलना गर्नुहोस्':'Compare saved areas'}</h2></div><button ref={compareCloseRef} type="button" onClick={()=>setSelected([])} aria-label={ne?'तुलना बन्द':'Close comparison'} className="icon-button focus-ring"><X size={19}/></button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{comparison.map(item=><Compare key={item.id} item={item} ne={ne}/>)}</div><div className="mt-4 rounded-lg bg-ink-950 p-5 text-white"><p className="text-xs uppercase tracking-wide text-ink-300">{ne?'अन्तर':'Difference'}</p><p className="numeral mt-2 text-3xl font-semibold">{formatDecimal(Math.abs(comparison[0].sqFt-comparison[1].sqFt))} <span className="text-xs text-ink-300">{ne?'वर्ग फिट':'sq ft'}</span></p></div></section></div>}
    {confirmClear&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-ink-950/60 sm:items-center sm:p-6" role="presentation"><section onKeyDown={trapFocus} className="w-full max-w-md rounded-t-lg bg-white p-6 shadow-soft sm:rounded-lg" role="dialog" aria-modal="true" aria-labelledby="clear-title"><p className="eyebrow text-red-700">{ne?'स्थानीय डाटा रिसेट':'Local data reset'}</p><h2 id="clear-title" className="mt-2 text-2xl font-bold text-ink-950">{ne?`सबै ${items.length} सुरक्षित परियोजना हटाउने?`:`Delete all ${items.length} saved projects?`}</h2><p className="mt-3 text-sm leading-6 text-ink-600">{ne?'यसले यो ब्राउजरको localStorage र IndexedDB बाट Napiyo डाटा हटाउँछ। आवश्यक भए पहिले ब्याकअप डाउनलोड गर्नुहोस्।':'This clears Napiyo data from localStorage and IndexedDB on this browser. Download a backup first if the projects matter.'}</p><div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button ref={clearCancelRef} type="button" onClick={()=>setConfirmClear(false)} className="button-secondary focus-ring">{ne?'रद्द':'Cancel'}</button><button type="button" onClick={()=>{void onClearAll();setConfirmClear(false);}} className="button-primary focus-ring !border-red-600 !bg-red-600">{ne?'सबै स्थानीय डाटा हटाउनुहोस्':'Delete all local data'}</button></div></section></div>}
  </div>;
};
const Action=({icon:Icon,label,onClick,danger=false}:{icon:typeof Copy;label:string;onClick:()=>void;danger?:boolean})=><button type="button" onClick={onClick} className={`focus-ring inline-flex min-h-11 items-center justify-center gap-1 bg-white text-[11px] font-semibold ${danger?'text-red-700':'text-ink-600'}`}><Icon size={14}/>{label}</button>;
const Compare=({item,ne}:{item:SavedItem;ne:boolean})=><div className="panel-muted p-5"><p className="text-sm font-semibold text-ink-700">{item.title}</p><p className="numeral mt-3 text-3xl font-semibold text-ink-950">{formatDecimal(item.sqFt)} <span className="text-xs text-ink-400">{ne?'वर्ग फिट':'sq ft'}</span></p><dl className="mt-5 space-y-4 border-t border-paper-200 pt-4"><div><dt className="metric-label">{ne?'पहाडी प्रणाली':'Hill system'}</dt><dd className="mt-1 text-sm font-semibold text-ink-800">{formatHillsWords(item.sqFt)}</dd></div><div><dt className="metric-label">{ne?'तराई प्रणाली':'Terai system'}</dt><dd className="mt-1 text-sm font-semibold text-ink-800">{formatTeraiWords(item.sqFt)}</dd></div>{item.source?.perimeterFt&&<div><dt className="metric-label">{ne?'परिधि':'Perimeter'}</dt><dd className="mt-1 text-sm font-semibold text-ink-800">{formatDecimal(item.source.perimeterFt)} ft</dd></div>}</dl></div>;
export default SavedScreen;
